---
- name: Template Airflow worker service file
  template:
    src: airflow-worker-edge.service.j2
    dest: /usr/lib/systemd/system/airflow-worker.service

- name: Add users to the airflow group # For impersonation
  become: yes
  user:
    name: "{{ item.user }}"
    groups: "{{ airflow_group }}"
    append: yes
  with_items: "{{ users }}"
  when: airflow_impersonation
  ignore_errors: true

- name: Add airflow to sudoers file # For impersonation
  become: yes
  lineinfile:
    path: /etc/sudoers
    line: 'airflow ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    backup: yes
  when: airflow_impersonation
  ignore_errors: true

- name: Change default beeline
  become: yes
  become_user: root
  shell: mv {{ airflow_install_dir }}/bin/beeline{,.airflow.bkp}
  ignore_errors: true