# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Start airflow scheduler service
  systemd:
    name: airflow-scheduler
    state: started
    enabled: true
    daemon_reload: true
