# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Stop airflow scheduler service
  systemd:
    name: airflow-scheduler
    state: stopped
    enabled: true
    daemon_reload: true

