# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: restart airflow webserver service
  systemd:
    name: airflow-webserver
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart airflow kerberos service
  systemd:
    name: airflow-kerberos
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart airflow flower service
  systemd:
    name: airflow-flower
    state: restarted
    enabled: true
    daemon_reload: true
