# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Stop airflow webserver service
  systemd:
    name: airflow-webserver
    state: stopped
    enabled: true
    daemon_reload: true

- name: Stop airflow kerberos service
  systemd:
    name: airflow-kerberos
    state: stopped
    enabled: true
    daemon_reload: true

- name: stop airflow flower service
  systemd:
    name: airflow-flower
    state: stopped
    enabled: true
    daemon_reload: true
