---
- name: start airflow worker service
  systemd:
    name: airflow-worker
    state: restarted
    enabled: true
    daemon_reload: true

- name: start airflow kerberos service
  systemd:
    name: airflow-kerberos
    state: restarted
    enabled: true
    daemon_reload: true
