---
- name: Ensures airflow configuration, log, dags and plugins directories
  become: yes
  become_user: root
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: "{{ item.mode }}"
    recurse: yes
  with_items:
    - { path: '{{ airflow_conf_dir }}', mode: '0755' }
    - { path: '{{ airflow_log_dir }}', mode: '0775' }
    - { path: '{{ airflow_child_process_log_dir }}', mode: '0775' }
    - { path: '{{ airflow_dag_dir }}', mode: '0755' }
    - { path: '{{ airflow_plugins_dir }}', mode: '0755' }

- name: Template airflow.cfg file
  template:
    src: "{{ airflow_conf_template }}.j2"
    dest: "{{ airflow_install_dir }}/airflow.cfg"

- name: Template airflow environment variables file
  template:
    src: airflow-env.j2
    dest: "{{ airflow_env_file }}"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Add users to the airflow group # For impersonation
  become: yes
  user:
    name: "{{ item.user }}"
    groups: "{{ airflow_group }}"
    append: yes
  with_items: "{{ users }}"
  when: airflow_impersonation
  ignore_errors: true

- name: Add airflow to sudoers file # For impersonation
  become: yes
  lineinfile:
    path: /etc/sudoers
    line: 'airflow ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    backup: yes
  when: airflow_impersonation
  ignore_errors: true
