---
- import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: install

- block:
    - import_role:
        name: tosit.tdp.utils.kerberos
        tasks_from: create_principal_keytab
      vars:
        principal: "airflow/{{ ansible_fqdn }}"
        keytab: "{{ airflow_kerberos.keytab }}"
        user: "{{ airflow_user }}"
        group: "{{ airflow_group }}"
        mode: "600"
      when: krb_create_principals_keytabs
