---
- name: "Install Airflow worker"
  hosts: airflow_worker
  strategy: linear
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: airflow_worker
    - import_role:
        name: tosit.tdp_extra.airflow.worker
        tasks_from: install
    - meta: clear_facts # noqa unnamed-task
